name: conduit_common_test
version: 2.0.0-b1
homepage: https://conduit.io
description: A collection of classes and function used for testing conduit and by the conduit test harness.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  conduit: ^2.0.0-0
  dcli: ^0.51.0
  settings_yaml: ^3.0.3
